### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by fighterpoul** [away4m/Vast-3.0#1]
Could you add License information, please? At now community has no idea when, where and how can use your code :-)

**Comment by away4m** [comment]
Hi, i just upgraded project to swift 4.0 and provide proper Podspec with license.I couldn't test migrated project yet and of course it needs sample, test and love :) Anyway I will improve it in time.

By the way it's MIT license and ir's not make any sense for me.I can use any type of license if more suitable for you.
